using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace ZeroAlloc.Flux.Generator;

/// <summary>
/// Emits the single <c>FluxDispatcher : IDispatcher</c> class. One concrete
/// <c>DispatchAsync(TAction)</c> overload is generated per unique action type discovered
/// across all reducers; the open generic <c>DispatchAsync&lt;TAction&gt;</c> overload acts
/// as a silent no-op fallback so unknown actions don't blow up at runtime.
/// </summary>
/// <remarks>
/// Fan-out strategy per concrete overload:
/// <list type="bullet">
///   <item><b>Single matching feature</b> — emit a straight-line return of
///         <c>store.UpdateAsync(action, static (s, a) =&gt; Reducer.On(s, a))</c>. The store
///         runs the reducer inside its atomic section. Pure sync, no state machine, no
///         allocations on the happy path.</item>
///   <item><b>Multiple matching features</b> — emit an <c>async ValueTask</c> body that
///         awaits each store's <c>UpdateAsync</c> in declaration order. ValueTask boxes once
///         only if a subscriber actually suspends.</item>
/// </list>
/// </remarks>
internal static class DispatcherEmitter
{
    /// <summary>The single class name the dispatcher always emits as.</summary>
    public const string DispatcherClassName = "FluxDispatcher";

    /// <summary>
    /// Renders the full <c>.cs</c> file source for <see cref="DispatcherClassName"/>.
    /// </summary>
    public static string Emit(
        ImmutableArray<FeatureInfo> features,
        ImmutableArray<ReducerInfo> reducers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using ZeroAlloc.Flux;");
        sb.AppendLine();
        sb.Append("namespace ").Append(StoreEmitter.GeneratedNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("internal sealed class ").Append(DispatcherClassName).AppendLine(" : IDispatcher");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IServiceProvider _sp;");
        sb.AppendLine();
        sb.Append("    public ").Append(DispatcherClassName).AppendLine("(IServiceProvider sp)");
        sb.AppendLine("    {");
        sb.AppendLine("        _sp = sp;");
        sb.AppendLine("    }");

        // Map action type FQN -> list of reducers that consume it (preserving declaration order).
        var byAction = new Dictionary<string, List<ReducerInfo>>(StringComparer.Ordinal);
        var actionOrder = new List<string>();
        foreach (var r in reducers)
        {
            if (!byAction.TryGetValue(r.ActionTypeFqn, out var list))
            {
                list = new List<ReducerInfo>();
                byAction.Add(r.ActionTypeFqn, list);
                actionOrder.Add(r.ActionTypeFqn);
            }
            list.Add(r);
        }

        // FeatureInfo lookup by state type FQN so we can resolve the matching store class name.
        var featureByState = new Dictionary<string, FeatureInfo>(StringComparer.Ordinal);
        foreach (var f in features) featureByState[f.FullyQualifiedName] = f;

        foreach (var actionFqn in actionOrder)
        {
            sb.AppendLine();
            EmitConcreteOverload(sb, actionFqn, byAction[actionFqn], featureByState);
        }

        // Interface entry point. Routes to the concrete overload for the supplied TAction via
        // a typeof-chain — for value-type TAction the JIT collapses this to a single direct
        // call (all other branches are dead code with constant-false guards). Reinterpret-cast
        // through Unsafe.As avoids any copy/boxing of the action payload.
        sb.AppendLine();
        sb.AppendLine("    public ValueTask DispatchAsync<TAction>(TAction action)");
        sb.AppendLine("    {");
        foreach (var actionFqn in actionOrder)
        {
            sb.Append("        if (typeof(TAction) == typeof(").Append(actionFqn).AppendLine("))");
            sb.AppendLine("        {");
            sb.Append("            return DispatchAsync(Unsafe.As<TAction, ").Append(actionFqn).AppendLine(">(ref action));");
            sb.AppendLine("        }");
        }
        sb.AppendLine("        return ValueTask.CompletedTask;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitConcreteOverload(
        StringBuilder sb,
        string actionFqn,
        List<ReducerInfo> reducersForAction,
        Dictionary<string, FeatureInfo> featureByState)
    {
        // Filter to reducers whose state-type matches a known feature; without a matching
        // FeatureInfo we can't resolve a store class name. Discovery already raises ZFLUX001
        // for stray reducers, so silently dropping them here is safe.
        var matching = new List<(ReducerInfo Reducer, FeatureInfo Feature)>();
        foreach (var r in reducersForAction)
        {
            if (featureByState.TryGetValue(r.StateTypeFqn, out var feat))
            {
                matching.Add((r, feat));
            }
        }

        sb.Append("    public ValueTask DispatchAsync(").Append(actionFqn).AppendLine(" action)");
        sb.AppendLine("    {");

        if (matching.Count == 0)
        {
            // Unreachable in practice — but emit a safe sync no-op.
            sb.AppendLine("        return ValueTask.CompletedTask;");
            sb.AppendLine("    }");
            return;
        }

        if (matching.Count == 1)
        {
            EmitSinglePath(sb, matching[0]);
            sb.AppendLine("    }");
            return;
        }

        EmitFanOutPath(sb, matching);
        sb.AppendLine("    }");
    }

    private static void EmitSinglePath(StringBuilder sb, (ReducerInfo Reducer, FeatureInfo Feature) pair)
    {
        var storeClass = pair.Feature.StoreClassName;
        var stateFqn = pair.Feature.FullyQualifiedName;
        var storeVar = LocalNameFor(pair.Feature);

        sb.Append("        var ").Append(storeVar).Append(" = (").Append(storeClass)
          .Append(")_sp.GetRequiredService<IStore<").Append(stateFqn).AppendLine(">>();");
        sb.Append("        return ").Append(storeVar).Append(".UpdateAsync(action, ");
        AppendReducerLambda(sb, pair.Reducer);
        sb.AppendLine(");");
    }

    private static void EmitFanOutPath(StringBuilder sb, List<(ReducerInfo Reducer, FeatureInfo Feature)> matching)
    {
        // Build a single async-local helper. Sequential awaits keep the ValueTask boxing
        // budget to zero on the all-sync path.
        sb.AppendLine("        return Fan(_sp, action);");
        sb.AppendLine();
        sb.Append("        static async ValueTask Fan(IServiceProvider sp, ")
          .Append(matching[0].Reducer.ActionTypeFqn)
          .AppendLine(" action)");
        sb.AppendLine("        {");

        // One local per reducer. Two can target features with the same bare name in different
        // namespaces, or the same feature from two reducer classes, so a repeat gets a suffix.
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        foreach (var (reducer, feature) in matching)
        {
            var storeClass = feature.StoreClassName;
            var stateFqn = feature.FullyQualifiedName;
            var storeVar = LocalNameFor(feature);
            for (var suffix = 2; !usedNames.Add(storeVar); suffix++)
            {
                storeVar = LocalNameFor(feature) + "_" + suffix.ToString(System.Globalization.CultureInfo.InvariantCulture);
            }

            sb.Append("            var ").Append(storeVar).Append(" = (").Append(storeClass)
              .Append(")sp.GetRequiredService<IStore<").Append(stateFqn).AppendLine(">>();");
            sb.Append("            await ").Append(storeVar).Append(".UpdateAsync(action, ");
            AppendReducerLambda(sb, reducer);
            sb.AppendLine(").ConfigureAwait(false);");
        }

        sb.AppendLine("        }");
    }

    /// <summary>
    /// Appends the reducer as a static lambda the store runs inside its atomic section. A
    /// non-capturing lambda is cached by the compiler, so dispatch allocates no delegate.
    /// </summary>
    private static void AppendReducerLambda(StringBuilder sb, ReducerInfo reducer)
    {
        sb.Append("static (s, a) => ")
          .Append(reducer.OwningTypeFqn).Append('.').Append(reducer.MethodName).Append("(s, a)");
    }

    /// <summary>
    /// Local variable name derived from the feature's bare type name, e.g.
    /// <c>store_CounterState</c>. It is not unique on its own: the fan-out path adds a suffix
    /// to a repeat within one method body.
    /// </summary>
    private static string LocalNameFor(FeatureInfo feature) => "store_" + feature.Name;
}
