using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;

namespace ZeroAlloc.Flux.Generator;

/// <summary>
/// Emits the single <c>FluxDispatcher : IDispatcher</c> class. One concrete
/// <c>DispatchAsync(TAction)</c> overload is generated per unique action type discovered
/// across all reducers; the open generic <c>DispatchAsync&lt;TAction&gt;</c> overload acts
/// as a silent no-op fallback so unknown actions don't blow up at runtime.
/// </summary>
/// <remarks>
/// Fan-out strategy per concrete overload:
/// <list type="bullet">
///   <item><b>Single matching feature</b> — emit a straight-line return of
///         <c>store.UpdateAsync(reducer.On(store.Value, action))</c>. Pure sync, no state
///         machine, no allocations on the happy path.</item>
///   <item><b>Multiple matching features</b> — emit an <c>async ValueTask</c> body that
///         awaits each store's <c>UpdateAsync</c> in declaration order. ValueTask boxes once
///         only if a subscriber actually suspends.</item>
/// </list>
/// </remarks>
internal static class DispatcherEmitter
{
    /// <summary>The single class name the dispatcher always emits as.</summary>
    public const string DispatcherClassName = "FluxDispatcher";

    /// <summary>
    /// Renders the full <c>.cs</c> file source for <see cref="DispatcherClassName"/>.
    /// </summary>
    public static string Emit(
        ImmutableArray<FeatureInfo> features,
        ImmutableArray<ReducerInfo> reducers)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using ZeroAlloc.Flux;");
        sb.AppendLine();
        sb.Append("namespace ").Append(StoreEmitter.GeneratedNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("internal sealed class ").Append(DispatcherClassName).AppendLine(" : IDispatcher");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IServiceProvider _sp;");
        sb.AppendLine();
        sb.Append("    public ").Append(DispatcherClassName).AppendLine("(IServiceProvider sp)");
        sb.AppendLine("    {");
        sb.AppendLine("        _sp = sp;");
        sb.AppendLine("    }");

        // Map action type FQN -> list of reducers that consume it (preserving declaration order).
        // SymbolEqualityComparer keys collapse equivalent INamedTypeSymbol instances.
        var byAction = new Dictionary<INamedTypeSymbol, List<ReducerInfo>>(SymbolEqualityComparer.Default);
        var actionOrder = new List<INamedTypeSymbol>();
        foreach (var r in reducers)
        {
            if (!byAction.TryGetValue(r.ActionType, out var list))
            {
                list = new List<ReducerInfo>();
                byAction.Add(r.ActionType, list);
                actionOrder.Add(r.ActionType);
            }
            list.Add(r);
        }

        // FeatureInfo lookup by StateType so we can resolve the matching store class name.
        var featureByState = new Dictionary<INamedTypeSymbol, FeatureInfo>(SymbolEqualityComparer.Default);
        foreach (var f in features) featureByState[f.TypeSymbol] = f;

        foreach (var actionType in actionOrder)
        {
            sb.AppendLine();
            EmitConcreteOverload(sb, actionType, byAction[actionType], featureByState);
        }

        // Generic fallback — no-op when no concrete overload matches the inferred TAction.
        sb.AppendLine();
        sb.AppendLine("    public ValueTask DispatchAsync<TAction>(TAction action)");
        sb.AppendLine("    {");
        sb.AppendLine("        return ValueTask.CompletedTask;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitConcreteOverload(
        StringBuilder sb,
        INamedTypeSymbol actionType,
        List<ReducerInfo> reducersForAction,
        Dictionary<INamedTypeSymbol, FeatureInfo> featureByState)
    {
        var actionFqn = actionType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        // Filter to reducers whose state-type matches a known feature; without a matching
        // FeatureInfo we can't resolve a store class name. Discovery already raises ZFLUX001
        // for stray reducers, so silently dropping them here is safe.
        var matching = new List<(ReducerInfo Reducer, FeatureInfo Feature)>();
        foreach (var r in reducersForAction)
        {
            if (featureByState.TryGetValue(r.StateType, out var feat))
            {
                matching.Add((r, feat));
            }
        }

        sb.Append("    public ValueTask DispatchAsync(").Append(actionFqn).AppendLine(" action)");
        sb.AppendLine("    {");

        if (matching.Count == 0)
        {
            // Unreachable in practice — but emit a safe sync no-op.
            sb.AppendLine("        return ValueTask.CompletedTask;");
            sb.AppendLine("    }");
            return;
        }

        if (matching.Count == 1)
        {
            EmitSinglePath(sb, matching[0]);
            sb.AppendLine("    }");
            return;
        }

        EmitFanOutPath(sb, matching);
        sb.AppendLine("    }");
    }

    private static void EmitSinglePath(StringBuilder sb, (ReducerInfo Reducer, FeatureInfo Feature) pair)
    {
        var storeClass = StoreEmitter.GetStoreClassName(pair.Feature);
        var stateFqn = pair.Feature.FullyQualifiedName;
        var storeVar = LocalNameFor(pair.Feature);

        sb.Append("        var ").Append(storeVar).Append(" = (").Append(storeClass)
          .Append(")_sp.GetRequiredService<IStore<").Append(stateFqn).AppendLine(">>();");
        sb.Append("        return ").Append(storeVar).Append(".UpdateAsync(")
          .Append(pair.Reducer.OwningTypeFqn).Append('.').Append(pair.Reducer.MethodName)
          .Append('(').Append(storeVar).AppendLine(".Value, action));");
    }

    private static void EmitFanOutPath(StringBuilder sb, List<(ReducerInfo Reducer, FeatureInfo Feature)> matching)
    {
        // Build a single async-local helper. Sequential awaits keep the ValueTask boxing
        // budget to zero on the all-sync path.
        sb.AppendLine("        return Fan(_sp, action);");
        sb.AppendLine();
        sb.Append("        static async ValueTask Fan(IServiceProvider sp, ")
          .Append(matching[0].Reducer.ActionType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
          .AppendLine(" action)");
        sb.AppendLine("        {");

        foreach (var (reducer, feature) in matching)
        {
            var storeClass = StoreEmitter.GetStoreClassName(feature);
            var stateFqn = feature.FullyQualifiedName;
            var storeVar = LocalNameFor(feature);

            sb.Append("            var ").Append(storeVar).Append(" = (").Append(storeClass)
              .Append(")sp.GetRequiredService<IStore<").Append(stateFqn).AppendLine(">>();");
            sb.Append("            var new").Append(storeVar).Append(" = ")
              .Append(reducer.OwningTypeFqn).Append('.').Append(reducer.MethodName)
              .Append('(').Append(storeVar).AppendLine(".Value, action);");
            sb.Append("            await ").Append(storeVar).Append(".UpdateAsync(new").Append(storeVar)
              .AppendLine(").ConfigureAwait(false);");
        }

        sb.AppendLine("        }");
    }

    /// <summary>
    /// Local variable name derived from the feature's type. Doesn't need to be unique
    /// globally — just unique within one emitted method body, which it always is because
    /// each fan-out targets distinct feature types.
    /// </summary>
    private static string LocalNameFor(FeatureInfo feature)
    {
        // Take just the unqualified type name. Strip the trailing 'State' if present to
        // keep the local readable (CounterState -> counter), otherwise keep the bare name.
        var name = feature.TypeSymbol.Name;
        return "store_" + name;
    }
}
