using System.Collections.Immutable;
using System.Text;

namespace ZeroAlloc.Flux.Generator;

/// <summary>
/// Emits the public <c>FluxServiceCollectionExtensions</c> class with the consumer-facing
/// <c>AddZeroAllocFlux</c> extension method. Wires the generated <c>FluxDispatcher</c> +
/// one <c>Store_*</c> per feature into the supplied <see cref="System.IServiceCollection"/>
/// at the requested <see cref="System.ServiceLifetime"/> (defaults to Scoped — see D-7).
/// </summary>
/// <remarks>
/// Features carrying an <c>InitialState</c> factory need a factory-based
/// <c>ServiceDescriptor</c> overload because their store constructor takes
/// <c>IServiceProvider</c>; default-init features use the simpler
/// <c>(serviceType, implementationType, lifetime)</c> form.
/// </remarks>
internal static class ServiceCollectionExtensionsEmitter
{
    /// <summary>The single class name the DI emitter always emits as.</summary>
    public const string ExtensionsClassName = "FluxServiceCollectionExtensions";

    /// <summary>
    /// Renders the full <c>.cs</c> file source for <see cref="ExtensionsClassName"/>.
    /// </summary>
    public static string Emit(ImmutableArray<FeatureInfo> features)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using ZeroAlloc.Flux;");
        sb.AppendLine();
        sb.Append("namespace ").Append(StoreEmitter.GeneratedNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("public static class ").AppendLine(ExtensionsClassName);
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddZeroAllocFlux(");
        sb.AppendLine("        this IServiceCollection services,");
        sb.AppendLine("        ServiceLifetime lifetime = ServiceLifetime.Scoped)");
        sb.AppendLine("    {");
        sb.Append("        services.Add(new ServiceDescriptor(typeof(IDispatcher), typeof(")
          .Append(DispatcherEmitter.DispatcherClassName).AppendLine("), lifetime));");

        foreach (var feature in features)
        {
            sb.AppendLine();
            EmitStoreRegistration(sb, feature);
        }

        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void EmitStoreRegistration(StringBuilder sb, FeatureInfo feature)
    {
        var storeClass = StoreEmitter.GetStoreClassName(feature);
        var stateFqn = feature.FullyQualifiedName;

        if (feature.InitialStateFactoryName is not null)
        {
            // Factory-init stores take IServiceProvider in their ctor; use the factory
            // overload so DI hands the provider through.
            sb.AppendLine("        services.Add(new ServiceDescriptor(");
            sb.Append("            typeof(IStore<").Append(stateFqn).AppendLine(">),");
            sb.Append("            sp => new ").Append(storeClass).AppendLine("(sp),");
            sb.AppendLine("            lifetime));");
        }
        else
        {
            // Parameterless ctor — use the type+type overload (DI will instantiate).
            sb.AppendLine("        services.Add(new ServiceDescriptor(");
            sb.Append("            typeof(IStore<").Append(stateFqn).AppendLine(">),");
            sb.Append("            typeof(").Append(storeClass).AppendLine("),");
            sb.AppendLine("            lifetime));");
        }
    }
}
