using System.Text;

namespace ZeroAlloc.Flux.Generator;

/// <summary>
/// Emits the per-feature <c>Store_&lt;Mangle&gt;</c> class that implements
/// <c>IStore&lt;TFeature&gt;</c>. Two code paths:
/// <list type="bullet">
///   <item><b>Struct features</b> — guarded by a private <c>object _lock</c>; the reducer runs,
///         and its result is written, under the monitor. Reads are lock-free.</item>
///   <item><b>Class features</b> — CAS retry loop via <see cref="System.Threading.Interlocked"/>
///         on the reference field: read, reduce, and swap only if the field still holds the
///         instance that was read, else retry. The reducer can run more than once per dispatch,
///         so it must be pure. No monitor needed.</item>
/// </list>
/// The emitted class lives in the synthetic <c>ZeroAlloc.Flux.Generated</c> namespace so the
/// mangled type name never collides with consumer code.
/// </summary>
internal static class StoreEmitter
{
    /// <summary>Namespace every generated Flux artefact lives in.</summary>
    public const string GeneratedNamespace = "ZeroAlloc.Flux.Generated";

    /// <summary>
    /// Class name for the store implementation of <paramref name="feature"/>. Format is
    /// <c>Store_&lt;FullyQualifiedName-without-global::-and-dots-replaced-by-underscores&gt;</c>.
    /// </summary>
    public static string GetStoreClassName(FeatureInfo feature)
    {
        var fqn = feature.FullyQualifiedName;
        const string globalPrefix = "global::";
        if (fqn.StartsWith(globalPrefix, System.StringComparison.Ordinal))
        {
            fqn = fqn.Substring(globalPrefix.Length);
        }
        return "Store_" + fqn.Replace('.', '_');
    }

    /// <summary>
    /// Renders the full <c>.cs</c> file source for a single feature's store.
    /// </summary>
    public static string Emit(FeatureInfo feature)
    {
        var className = GetStoreClassName(feature);
        var stateType = feature.FullyQualifiedName;
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using ZeroAlloc.Flux;");
        sb.AppendLine();
        sb.Append("namespace ").Append(GeneratedNamespace).AppendLine(";");
        sb.AppendLine();
        sb.Append("internal sealed class ").Append(className)
          .Append(" : IStore<").Append(stateType).AppendLine(">");
        sb.AppendLine("{");

        if (feature.IsStruct)
        {
            sb.AppendLine("    private readonly object _lock = new();");
        }
        sb.Append("    private ").Append(stateType).AppendLine(" _state;");
        sb.AppendLine();

        // Constructor
        if (feature.InitialStateFactoryName is { } factory)
        {
            sb.Append("    public ").Append(className).AppendLine("(System.IServiceProvider sp)");
            sb.AppendLine("    {");
            sb.Append("        _state = ").Append(stateType).Append('.').Append(factory).AppendLine("(sp);");
            sb.AppendLine("    }");
        }
        else
        {
            sb.Append("    public ").Append(className).AppendLine("()");
            sb.AppendLine("    {");
            sb.Append("        _state = new ").Append(stateType).AppendLine("();");
            sb.AppendLine("    }");
        }
        sb.AppendLine();

        sb.Append("    public ").Append(stateType).AppendLine(" Value => _state;");
        sb.AppendLine();
        sb.Append("    public event Action<").Append(stateType).AppendLine(">? StateChanged;");
        sb.AppendLine();

        // The reducer runs inside the atomic section, on the state it replaces. Computing the new
        // state outside it and writing it afterwards loses concurrent updates, see #131.
        sb.AppendLine("    internal ValueTask UpdateAsync<TAction>(");
        sb.AppendLine("        TAction action,");
        sb.Append("        Func<").Append(stateType).Append(", TAction, ").Append(stateType).AppendLine("> reducer)");
        sb.AppendLine("    {");
        sb.Append("        ").Append(stateType).AppendLine(" newState;");
        if (feature.IsStruct)
        {
            sb.AppendLine("        lock (_lock)");
            sb.AppendLine("        {");
            sb.AppendLine("            newState = reducer(_state, action);");
            sb.AppendLine("            _state = newState;");
            sb.AppendLine("        }");
        }
        else
        {
            // ReferenceEquals, not the record's value equality: the swap succeeded only when
            // the field still holds the very instance the reducer ran on.
            sb.AppendLine("        while (true)");
            sb.AppendLine("        {");
            sb.AppendLine("            var oldState = System.Threading.Volatile.Read(ref _state);");
            sb.AppendLine("            newState = reducer(oldState, action);");
            sb.AppendLine("            if (object.ReferenceEquals(");
            sb.AppendLine("                System.Threading.Interlocked.CompareExchange(ref _state, newState, oldState),");
            sb.AppendLine("                oldState))");
            sb.AppendLine("            {");
            sb.AppendLine("                break;");
            sb.AppendLine("            }");
            sb.AppendLine("        }");
        }
        sb.AppendLine("        StateChanged?.Invoke(newState);");
        sb.AppendLine("        return ValueTask.CompletedTask;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
